spring:
  application:
    name: tlias
  datasource:
    url: jdbc:mariadb://localhost:3306/tlias
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 20040927
  servlet:
    multipart:
      max-file-size: 10MB #最大单个文件大小
      max-request-size: 100MB #最大请求总大小(包括所有文件和表单数据)

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 配置数据库事物管理日子级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: cangli
    region: cn-beijing